name: Deploy App to Dev

# trigger: on push to `main` branch, AND only on changes to `app/*` files
on:
  push:
    # TODO change back to branches: [main]
    branches: [github-actions-fleek-app]
    paths:
      - "app/*"
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # see https://docs.fleek.co/fleek-cli/github-actions/#sample-action-deploy-action
      # note - env variables are configured in fleek
      - name: Deploy app to fleek from review
        working-directory: ./app/fleek/review/
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
