name: Deploy App to Review
# trigger: on push to `main` branch, AND only on changes to `app/*` files
on:
  push:
    # TODO change back to branches: [main]
    branches: [github-actions-fleek-app]
    # paths:
    #   - "app/**"
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: |
          git fetch
          Checkout staging-app
        run: git checkout origin/staging-app
      - name: Merge changes from main
        run: git merge --ff-only origin/main
      - name: push to staging-app
        run: git push
