name: Deploy App to Review
# trigger: on push to `main` branch, AND only on changes to `app/*` files
on:
  push:
    # TODO change back to branches: [main]
    branches: [github-actions-fleek-app]
    # paths:
    #   - "app/**"
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge changes from main and push
        run: |
          git fetch
          git checkout origin/staging-app
          git merge --ff-only origin/main
          git push
