name: Release and Deploy Passport

## To use this in a new repo
## 1. Copy this file
## 2. Configure secrets shown below
 #    PULUMI_ACCESS_TOKEN
 #    AWS_ACCESS_KEY_ID_PRODUCTION
 #    AWS_ACCESS_KEY_ID_STAGING
 #    AWS_SECRET_ACCESS_KEY_PRODUCTION
 #    AWS_SECRET_ACCESS_KEY_STAGING
 #    ECR_URL_PRODUCTION
 #    ECR_URL_STAGING
 #    ROUTE53_ZONE_ID_PRODUCTION
 #    ROUTE53_ZONE_ID_STAGING
 #    IAM_SERVER_SSM_ARN_PRODUCTION
 #    IAM_SERVER_SSM_ARN_STAGING
## 3. Update input values ("with") below
## 4. Create an environment called "production" and add Required Reviewers

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit to run on, leave blank to use current HEAD"
        type: string
        required: false

env:
  refspec: ${{ inputs.commit || github.ref }}

jobs:
  deploy_passport:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.refspec }}
      #uses: gitcoinco/gh-workflows/.github/workflows/release_and_deploy.yml@main
      #with:
      #  refspec: ${{ inputs.commit }}
      #  repo_owner: gitcoinco
      #  repo_name: passport
      #  staging_frontend_branch: test_frontend_build_staging
      #  production_frontend_branch: test_frontend_build_prod
      #  staging_domain: staging.passport-iam.gitcoin.co
      #  production_domain: passport-iam.gitcoin.co
      #  ecr_repository: passport
      #secrets: inherit
